version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
    links:
      - mysql
    container_name: project_app

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - save:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - 85:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootroot

  drawer:
    image: php:7.2-apache
    ports:
      - 8001:80
    volumes:
      - ./drawer:/var/www/html
    container_name: Drawer

  sort:
    image: php:7.2-apache
    ports:
      - 8002:80
    volumes:
      - ./sort:/var/www/html
    container_name: Sorter

  commandstring:
    image: php:7.2-apache
    ports:
      - 8003:80
    volumes:
      - ./commandstring:/var/www/html
    container_name: CommandString

volumes:
  save: